
# This is a basic workflow to help you get started with Actions

name: AnimationApp4a

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Installing Node
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12 
        
    - name: installing surge
      run:  yarn global add surge
      
    - name: deploying surge app
      run:  yarn surge ./home/talibsarwar/Desktop/BootCamp/AnimationApp4a/AnimationApp4a/node_modules/.bin/surge http://animationapp4a.surge.sh/ --token ${{secrets.SURGE_TOKEN}}
